name: Notify Telegram on Release

on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Telegram with button
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -H "Content-Type: application/json" \
          -d "{
            \"chat_id\": \"-1003071555867\",
            \"parse_mode\": \"Markdown\",
            \"text\": \"🔥 *Aggiornamento Disponibile!* 🔥%0A-Nuova Release per *NFC Fucker*-%0A*Versione:* ${{ github.event.release.name }}%0AControlla il Changelog per le novità!\",
            \"reply_markup\": {
              \"inline_keyboard\": [[
                {\"text\": \"🔗 Vai al sito\", \"url\": \"https://macolab.github.io/ESP32C3-NFC-FUCKER/\"}
              ]]
            }
          }"
