name: Test Telegram Bot

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Send test message
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -H "Content-Type: application/json" \
          -d "{
            \"chat_id\": \"-1003071555867\",
            \"parse_mode\": \"Markdown\",
            \"text\": \"🔥 Test messaggio dal bot 🔥\",
            \"reply_markup\": {
              \"inline_keyboard\": [[
                {\"text\": \"🔗 Vai al sito\", \"url\": \"https://macolab.github.io/ESP32C3-NFC-FUCKER/\"}
              ]]
            }
          }"
